# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: G-Web
email: gareth@garethwestern.com
description: >- # this means to ignore newlines until "baseurl:"
        @gareth's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garethwestern.com"
github_username:  gdubya
logo: images/gareth.jpg
feed:
  path: atom.xml
locale: en-GB
read_time: true
google_analytics: UA-113692-1
mastodon: ma0gw@mastodon.social  

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/light.css"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Search
search_full_content: true

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      comments: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginated
  - jekyll-seo-tag
  - jekyll-gist

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: https://github.com/gdubya
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/gwestern
    icon: fab fa-linkedin
  - title: BlueSky
    url: https://bsky.app/profile/garethwestern.com
    icon: fa-brands fa-bluesky
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Include these files/folders that are excluded by default
include: [ "/.well-known" ]
